-- GENERATED by scripts/gen-seed.ts from evals/ananya-handlooms.yaml. Do not edit by hand.
-- Demo client: Ananya Handlooms (fictional).
begin;
insert into public.organizations (id, name, business_type, plan, monthly_conversation_quota, timezone) values ('00000000-0000-4000-8000-00000000a001', 'Ananya Handlooms', 'handloom saree store', 'starter', 2000, 'Asia/Kolkata') on conflict (id) do nothing;
insert into public.bots (id, org_id, name, public_key, test_token, status, website_url, allowed_origins, tone, greeting, nudge, suggested_questions, branding, notify_emails, notify_whatsapp, fallback_contact, privacy_url) values ('00000000-0000-4000-8000-00000000b001', '00000000-0000-4000-8000-00000000a001', 'Ananya Handlooms website', 'pk_ananya_demo_0001', 'tt_ananya_demo_private_0001_change_me_in_production', 'draft', 'https://ananyahandlooms.example', array['http://localhost:3000', 'http://localhost:4173', 'http://127.0.0.1:4173']::text[], 'Warm, respectful and simple, like a helpful shop assistant in Kanchipuram. Short sentences. Never pushy.', 'Vanakkam! I''m Meera from Ananya Handlooms. Ask me about sarees, delivery, returns or blouse stitching.', 'Hi! Questions about sizes, delivery or returns?', array['Is cash on delivery available?', 'How long does delivery take?', 'What is your return policy?']::text[], '{"primary_color":"#9f1239","avatar_url":null,"assistant_name":"Meera","position":"right","theme":"auto","show_powered_by":true}'::jsonb, array['owner@ananyahandlooms.example']::text[], array['+919876543210']::text[], '{"phone":"+91 98765 43210","whatsapp":"+91 98765 43210","email":"hello@ananyahandlooms.example"}'::jsonb, 'https://ananyahandlooms.example/privacy') on conflict (id) do nothing;
insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values ('00000000-0000-4000-8000-00000000b001', 'policy', 'Payment options', null, '- Cash on delivery (COD) is available across India on all orders. No extra charge for COD.
- We also accept UPI, debit/credit cards and net banking at checkout.
- COD is NOT available for international orders. International orders must be prepaid.', 'approved', 62);
insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values ('00000000-0000-4000-8000-00000000b001', 'policy', 'Shipping and delivery', null, '- Orders are dispatched from our Kanchipuram store within 1 working day.
- Delivery to Puducherry: 3–4 working days.
- Delivery to Chennai: 2–3 working days.
- Delivery to the rest of India: 5–7 working days.
- Shipping within India is free on orders above ₹1,999. Below that, shipping is ₹99.
- International shipping: we currently ship only to the UAE. Delivery takes 7–10 days. Shipping costs ₹1,450 per 2 sarees. No COD abroad.
- A tracking link is sent by SMS and email once the order is dispatched.', 'approved', 131);
insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values ('00000000-0000-4000-8000-00000000b001', 'policy', 'Returns and exchanges', null, '- Free returns within 7 days of delivery, if the saree is unused and the tags are intact.
- Exchanges follow the same 7-day rule.
- Refunds go to the original payment method within 5–7 working days after we receive the return. COD orders are refunded by UPI or bank transfer.
- Sarees with custom-stitched blouses cannot be returned.', 'approved', 85);
insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values ('00000000-0000-4000-8000-00000000b001', 'faq', 'Blouse stitching and sizes', null, 'Q: Do you stitch blouses? What sizes?
A: Yes. Blouse sizes 32 to 44 are available. Blouse stitching costs ₹650 and adds 5 working days to delivery. Fall and pico costs ₹150.', 'approved', 45);
insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values ('00000000-0000-4000-8000-00000000b001', 'faq', 'Bulk and wedding orders', null, 'Q: Do you take bulk orders for weddings or corporate gifting?
A: Yes, for 10 or more sarees our team prepares a special quote. Share your name and phone number and the team will call you.', 'approved', 47);
insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values ('00000000-0000-4000-8000-00000000b001', 'faq', 'Saree care', null, 'Q: How do I wash my saree?
A: Silk sarees: dry clean only. Cotton sarees: gentle hand wash in cold water, dry in shade.', 'approved', 30);
insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values ('00000000-0000-4000-8000-00000000b001', 'policy', 'Store and contact', null, '- Store address: 12 Gandhi Street, Kanchipuram, Tamil Nadu 631501.
- Store hours: Monday to Saturday, 10 am to 7 pm. Closed on Sunday.
- Phone and WhatsApp: +91 98765 43210. Email: hello@ananyahandlooms.example', 'approved', 53);
insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values ('00000000-0000-4000-8000-00000000b001', 'product', 'Kanchipuram Silk Saree – Temple Border, Maroon', 'https://ananyahandlooms.example/products/kanchipuram-silk-temple-maroon', 'Price: ₹12,500. Pure mulberry silk with zari temple border. Length 6.3 m including blouse piece. In stock.', 'approved', 28);
insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values ('00000000-0000-4000-8000-00000000b001', 'product', 'Kanchi Cotton Saree – Mustard Checks', 'https://ananyahandlooms.example/products/kanchi-cotton-mustard-checks', 'Price: ₹1,850. Handwoven cotton, light and breathable for daily wear. 5.5 m plus 0.8 m blouse piece. In stock.', 'approved', 29);
insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values ('00000000-0000-4000-8000-00000000b001', 'product', 'Chettinad Cotton Saree – Indigo', 'https://ananyahandlooms.example/products/chettinad-cotton-indigo', 'Price: ₹1,650. Chettinad cotton with contrast border. In stock.', 'approved', 17);
insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values ('00000000-0000-4000-8000-00000000b001', 'product', 'Soft Silk Saree – Peacock Green', 'https://ananyahandlooms.example/products/soft-silk-peacock-green', 'Price: ₹4,200. Lightweight soft silk, easy to drape. Only a few left.', 'approved', 19);
insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values ('00000000-0000-4000-8000-00000000b001', 'product', 'Bridal Kanjivaram – Red and Gold', 'https://ananyahandlooms.example/products/bridal-kanjivaram-red-gold', 'Price: ₹28,000. Heavy bridal Kanjivaram with pure zari. Made to order: ready in 3 weeks.', 'approved', 23);
commit;
