import type { Metadata } from "next";

export const metadata: Metadata = { title: "Chat privacy notice", robots: { index: true, follow: true } };

/** Default visitor privacy notice linked from the widget (each bot can link its own instead). */
export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-10 text-[15px] leading-relaxed text-slate-800">
      <h1 className="text-2xl font-semibold">Chat assistant privacy notice</h1>
      <p className="mt-4">This chat assistant is run by the business whose website you are on, using Botly. This notice explains what happens to what you type.</p>
      <h2 className="mt-6 font-semibold">What we collect and why</h2>
      <ul className="mt-2 list-disc space-y-1 pl-5">
        <li>Your messages, the page you were on and a random visitor ID, to answer your questions and let the business see and improve the answers.</li>
        <li>Your name, phone number and (if you choose) email, only when you ask to be contacted, so the business can call or message you back.</li>
        <li>We don&apos;t ask for payment details, OTPs, passwords or ID numbers. Please don&apos;t share them in the chat.</li>
      </ul>
      <h2 className="mt-6 font-semibold">Who can see it</h2>
      <p className="mt-2">Only the business and Botly (who operates the assistant for them). Answers are generated by an AI model from Anthropic, which processes the conversation to write each reply.</p>
      <h2 className="mt-6 font-semibold">How long we keep it</h2>
      <p className="mt-2">Conversations are kept for up to 12 months unless the business sets a shorter period.</p>
      <h2 className="mt-6 font-semibold">Your choices</h2>
      <p className="mt-2">You can ask the business to delete your chat and contact details at any time, using the contact details on their website. We follow the spirit of India&apos;s Digital Personal Data Protection Act: a clear purpose, as little data as possible, and deletion on request.</p>
    </main>
  );
}
