import type { Metadata } from "next";
import { MarketingShell } from "@/components/marketing/shell";
import { TRIAL } from "@/lib/plans";

export const metadata: Metadata = { title: "Terms of Service · Botly", robots: { index: true, follow: true } };

// TEMPLATE: have a lawyer review before relying on it. Set BUSINESS_LEGAL_NAME, BUSINESS_CITY, SUPPORT_EMAIL.
export default function Terms() {
  const name = process.env.BUSINESS_LEGAL_NAME || "Botly";
  const email = process.env.SUPPORT_EMAIL || "support@your-domain";
  const city = process.env.BUSINESS_CITY || "Chennai";
  return (
    <MarketingShell>
      <main className="mx-auto max-w-3xl px-4 py-12 text-[15px] leading-relaxed text-slate-800">
        <h1 className="text-3xl font-bold">Terms of Service</h1>
        <p className="mt-2 text-sm text-slate-500">These terms are between you (the business using Botly) and {name}.</p>
        <h2 className="mt-8 text-lg font-semibold">1. The service</h2>
        <p>Botly provides an AI chat assistant for your website, built from information you provide and from your business&apos;s public pages. Answers are generated by AI. We work to keep them grounded in your approved information, but you are responsible for reviewing that information and the assistant&apos;s behaviour on your site.</p>
        <h2 className="mt-6 text-lg font-semibold">2. Your account and content</h2>
        <p>You must represent the business you set up and have the right to use the information and links you give us. You keep ownership of your content. You give us permission to process it to run the service. Don&apos;t use Botly for unlawful, deceptive or harmful purposes, or to collect card numbers, OTPs, passwords or government ID numbers.</p>
        <h2 className="mt-6 text-lg font-semibold">3. Free trial</h2>
        <p>New accounts get a free trial of {TRIAL.days} days including {TRIAL.replies} AI replies, once per email address. When the trial ends, the assistant shows your contact details instead of AI replies until you choose a paid plan.</p>
        <h2 className="mt-6 text-lg font-semibold">4. Plans, payment and cancellation</h2>
        <p>Paid plans are billed monthly in advance through Razorpay, plus applicable GST. Plans renew automatically until cancelled. You can cancel any time from Billing; your plan stays active until the end of the paid period. Fees already paid are not refunded except where required by law. Monthly conversation limits apply per plan; when reached, the assistant shows your contact details until the next month or an upgrade.</p>
        <h2 className="mt-6 text-lg font-semibold">5. Data</h2>
        <p>Conversations and leads are stored to provide the service and are visible to you and to us for support. See the Privacy Policy. You can export your data and ask us to delete a visitor&apos;s data at any time.</p>
        <h2 className="mt-6 text-lg font-semibold">6. Availability and liability</h2>
        <p>We aim for high availability but the service is provided &quot;as is&quot;. To the extent permitted by law, our total liability for any claim is limited to the fees you paid in the three months before the claim. We are not liable for indirect or consequential losses, or for decisions made based on AI replies.</p>
        <h2 className="mt-6 text-lg font-semibold">7. Suspension</h2>
        <p>We may suspend accounts that break these terms, fail to pay, or put the service or others at risk.</p>
        <h2 className="mt-6 text-lg font-semibold">8. Changes and law</h2>
        <p>We may update these terms and will tell you by email about material changes. These terms are governed by the laws of India, with courts in {city} having jurisdiction.</p>
        <p className="mt-8">Questions: <a className="underline" href={`mailto:${email}`}>{email}</a></p>
      </main>
    </MarketingShell>
  );
}
