/**
 * Generates supabase/seed.sql from the fixture in evals/ananya-handlooms.yaml,
 * so the demo bot and the eval set can never drift apart.
 *   npx tsx scripts/gen-seed.ts
 */
import { writeFileSync } from "node:fs";
import { loadEvalFile } from "../lib/eval/fixture";
import { estimateTokens } from "../lib/tokens";

const file = loadEvalFile("evals/ananya-handlooms.yaml");
const f = file.fixture!;
const q = (v: unknown) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a: string[]) => `array[${a.map(q).join(", ")}]::text[]`;
const json = (o: unknown) => `${q(JSON.stringify(o))}::jsonb`;

const lines: string[] = [];
lines.push("-- GENERATED by scripts/gen-seed.ts from evals/ananya-handlooms.yaml. Do not edit by hand.");
lines.push("-- Demo client: Ananya Handlooms (fictional).");
lines.push("begin;");
lines.push(`insert into public.organizations (id, name, business_type, plan, monthly_conversation_quota, timezone) values (${q(f.org.id)}, ${q(f.org.name)}, ${q(f.org.business_type)}, ${q(f.org.plan)}, ${f.org.monthly_conversation_quota}, ${q(f.org.timezone)}) on conflict (id) do nothing;`);
const b = f.bot;
lines.push(
  `insert into public.bots (id, org_id, name, public_key, test_token, status, website_url, allowed_origins, tone, greeting, nudge, suggested_questions, branding, notify_emails, notify_whatsapp, fallback_contact, privacy_url) values (${q(b.id)}, ${q(f.org.id)}, ${q(b.name)}, ${q(b.public_key)}, ${q(b.test_token)}, ${q(b.status)}, ${q(b.website_url)}, ${arr(b.allowed_origins)}, ${q(b.tone)}, ${q(b.greeting)}, ${q(b.nudge)}, ${arr(b.suggested_questions)}, ${json(b.branding)}, ${arr(b.notify_emails)}, ${arr(b.notify_whatsapp)}, ${json(b.fallback_contact)}, ${q(b.privacy_url)}) on conflict (id) do nothing;`,
);
for (const k of f.knowledge) {
  lines.push(
    `insert into public.knowledge_sources (bot_id, type, title, url, content, status, token_count) values (${q(b.id)}, ${q(k.type)}, ${q(k.title)}, ${q(k.url ?? null)}, ${q(k.content.trim())}, 'approved', ${estimateTokens(k.content)});`,
  );
}
lines.push("commit;");
writeFileSync("supabase/seed.sql", lines.join("\n") + "\n");
console.log(`Wrote supabase/seed.sql (${f.knowledge.length} knowledge sources).`);
